import { config } from "dotenv";
config();
export const configs = {
  PORT: process.env.PORT,
  DB_URL: process.env.DB_URL,

  SALT: +process.env.SALT,

  JWT_CANDIDATE_ACCESS_SECRET: process.env.JWT_CANDIDATE_ACCESS_SECRET,
  JWT_CANDIDATE_REFRESH_SECRET: process.env.JWT_CANDIDATE_REFRESH_SECRET,

  JWT_HR_ACCESS_SECRET: process.env.JWT_HR_ACCESS_SECRET,
  JWT_HR_REFRESH_SECRET: process.env.JWT_HR_REFRESH_SECRET,

  JWT_COMPANY_ACCESS_SECRET: process.env.JWT_COMPANY_ACCESS_SECRET,
  JWT_COMPANY_REFRESH_SECRET: process.env.JWT_COMPANY_REFRESH_SECRET,

  JWT_CANDIDATE_FORGOT_SECRET: process.env.JWT_CANDIDATE_FORGOT_SECRET,
  JWT_HR_FORGOT_SECRET: process.env.JWT_HR_FORGOT_SECRET,
  JWT_COMPANY_FORGOT_SECRET: process.env.JWT_COMPANY_FORGOT_SECRET,

  JWT_CANDIDATE_VERIFY_SECRET: process.env.JWT_CANDIDATE_VERIFY_SERCRET,
  JWT_HR_VERIFY_SECRET: process.env.JWT_HR_VERIFY_SECRET,
  JWT_COMPANY_VERIFY_SECRET: process.env.JWT_COMPANY_VERIFY_SECRET,

  JWT_ADMIN_ACCESS_SECRET: process.env.JWT_ADMIN_ACCESS_SECRET,
  JWT_ADMIN_REFRESH_SECRET: process.env.JWT_ADMIN_REFRESH_SECRET,
  JWT_ADMIN_FORGOT_SECRET: process.env.JWT_ADMIN_FORGOT_SECRET,
  JWT_ADMIN_VERIFY_SECRET: process.env.JWT_ADMIN_VERIFY_SECRET,

  NO_REPLY_EMAIL: process.env.NO_REPLY_EMAIL,
  NO_REPLY_PASSWORD: process.env.NO_REPLY_PASSWORD,

  FRONT_URL: process.env.FRONT_URL,

  AWS_S3_BUCKET_NAME: process.env.AWS_S3_BUCKET_NAME,
  AWS_S3_REGION: process.env.AWS_S3_REGION,
  AWS_S3_BUCKET_URL: process.env.AWS_S3_BUCKET_URL,
  AWS_S3_ACL: process.env.AWS_S3_ACL,

  AWS_ACCESS_KEY: process.env.AWS_ACCESS_KEY,
  AWS_SECRET_KEY: process.env.AWS_SECRET_KEY,
};
