name: Back Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Backend Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run deploy on remote
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ vars.HOST }}
          username: ${{ secrets.USERNAME }}
          key: '${{ secrets.KEY }}'
          port: "22"
          command_timeout: "30m"
          script: |
            export FLOWER_LOGIN='${{ secrets.FLOWER_LOGIN }}'
            export FLOWER_PWD='${{ secrets.FLOWER_PWD }}'
            cd project
            git pull git@github.com:UPCoD-UNKD/proj-buxonline.git main
            cd backend
            ls -al
